### ISSUE TITLE
.gitmodules missing

### ISSUE THREAD

**Issue by Foltik** [sriRacha21/Rutgers-kun3#12]
The `.gitmodules` file is missing in the repo, which results in an error when trying to fetch the submodule for the bbt script:

```
Rutgers-kun3> git submodule update --init --recursive
fatal: No url found for submodule path 'scripts/fa1939febb310bcb6f8e9809604a4211' in .gitmodules
```

**Comment by sriRacha21** [comment]
fixed by commit 0db6d96497d1eec6505d9d1993acaa5a0ad194bc
