### ISSUE TITLE
!agreementsetupslim sometimes doesn’t remove other reactions

### ISSUE THREAD

**Issue by rzmk** [sriRacha21/Rutgers-kun3#21]
Implementing a way to clear up any reactions other than that of Rutgers-Kun may be optimal. Otherwise, people haven't been able to get a DM from Rutgers-Kun once another user's reaction has been added and not removed.
Example:
![image](https://user-images.githubusercontent.com/30333942/104894594-e59e4300-5942-11eb-8c1b-6ac25cc7dcf8.jpeg)

**Comment by sriRacha21** [comment]
resolved: 10683e96da6c19323af7d2c271724af9fd37bf87
