### ISSUE TITLE
LaTeX thing

### ISSUE THREAD

**Issue by sangjun0216** [sriRacha21/Rutgers-kun3#24]
![image](https://user-images.githubusercontent.com/20614323/105614858-388c5600-5d9a-11eb-9e4b-69d441ecfeeb.png)
Rutgers-kun repeats long LaTeX commands and possibly clutters up chat

**Comment by sriRacha21** [comment]
Fixed by commit 2911e36ea4628471e33c5f9c930a6ef398c299d1
