### ISSUE TITLE
ESLint setup

### ISSUE THREAD

**Issue by sriRacha21** [sriRacha21/Rutgers-kun3#30]
First step to typescript rewrite. Need to clean up and make the code all consistent.

**Comment by kirtanp98** [comment]
I would add a pre commit hook, so the linting rules will be enfored

**Comment by kirtanp98** [comment]
https://travis-ci.com/github/sriRacha21/Rutgers-kun3/builds/215154826

Build failing

**Comment by sriRacha21** [comment]
WIP PR #32 

Remember to squash commits

**Comment by sriRacha21** [comment]
Merged! Will monitor for errors and close when it seems stable.
