### ISSUE TITLE
Create tag so that LaTeX images can be marked as spoilers

### ISSUE THREAD

**Issue by sangjun0216** [sriRacha21/Rutgers-kun3#35]
do it

**Comment by sriRacha21** [comment]
8d685f81145d96d1d29cc9704f1087dbe7dd7cd4

**Comment by sriRacha21** [comment]
Implementation is a little messy since Discord doesn't support sending a mix of spoiler and non-spoiler attachments in a single message. May reopen and adjust behavior if Discord ever changes this.
