### ISSUE TITLE
Changing Nicknames

### ISSUE THREAD

**Issue by wunheather** [sriRacha21/Rutgers-kun3#36]
Could you add a thing where the bot would request in DMs for the person to enter their full names and the bot will change the nicknames to that?

**Comment by sriRacha21** [comment]
Interesting idea. What would be the trigger for this? Just when the user joins the server?

**Comment by wunheather** [comment]
After !agree, that way it is consistent with the netid, and roles info

**Comment by sriRacha21** [comment]
This is out of scope of this project. I recommend suggesting to members to change their nickname in your agreement or rules channels prior to joining the server, or using `!setroleresponse` to DM the user to change their nickname upon receiving their role.
