### ISSUE TITLE
tty support for owners

### ISSUE THREAD

**Issue by sriRacha21** [sriRacha21/Rutgers-kun3#6]
use gotty?

**Comment by Foltik** [comment]
Do you mean from within discord, or from the web?

**Comment by Foltik** [comment]
For gotty you'd need to have a domain with a letsencrypt cert, because I'm pretty sure some browsers will choke with websockets on a self signed cert

**Comment by sriRacha21** [comment]
Andrew brought this up but I was thinking maybe you do !gotty and it'll respond with a URL that you can use with it. We can use the rutgersesports domain for it.
